version: "3.6"

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/:/etc/prometheus/
    command: >-
      --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090
    network_mode: "host"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=p2pcdn
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    network_mode: "host"
